### ISSUE TITLE
Design wireframes for new website

### ISSUE THREAD

**Issue by azan-m** [SEG4910-Capstone/ros-workspace#36]
We need to design a new website for the Autonomous vehicle club website. This is the current website: https://www.uocav.ca/

The first step is to generate wireframes for each section. The tasks will follow as:

- [x] Generate wireframe for "Home" page/section
- [x] Generate wireframe for "Team" page/section
- [x] Generate wireframe for "Partners" page/section
~~Generate wireframe for "Blogs" page/section~~
~~Generate wireframe for "Docs" page/section (do we want to keep it as a simple link to the documentation?)~~

**Comment by Aduno** [comment]
For the docs section, we can keep it as is

**Comment by Ife-deb** [comment]
The current Blogs page has no content, so ig we ignore for now?

**Comment by Aduno** [comment]
Blogs section can be removed

**Comment by Aduno** [comment]
Link to wireframe: https://www.figma.com/design/cXPjzOUu95xaMMzs46MRWS/uOCAV?node-id=7-1337&t=FKGpRj8DW52G59Dt-1
