### ISSUE TITLE
Test Motor controller with Encoder feedback

### ISSUE THREAD

**Issue by Aduno** [SEG4910-Capstone/ros-workspace#38]
Todo:
Need to test out the encoder with our motor controller. 
1. To do this, we need to connect the pins as defined here
https://uottawa.sharepoint.com/sites/uOttawaConnectedAutonomousVehicles/Shared%20Documents/Electrical%20And%20Embedded/2023-2024/Motor%20Encoder%20Research.docx?d=waaea2076daba4195b577f7b6e4328ef1&csf=1&web=1&e=LhLyF7

2. Need to enable the encoder in the motor controller by the following "To test the encoder, use the PC utility to enable the encoder and set its number of Pulses Per Revolution (PPR). Go to the Utility’s Run tab, enable the Encoder Count in the chart.
Make a full turn of the motor shaft by hand. Verify that the counter has changed by the number of PPR * 4."

**Comment by MohanadAhmed123** [comment]
Tested motor encoder feedback using the motor controller drivers and it's been confirmed to work. 

https://github.com/user-attachments/assets/b00a247c-ba11-4b99-a1a2-09e6aa608a6c
