### ISSUE TITLE
Migration to arm64

### ISSUE THREAD

**Issue by uocav** [SEG4910-Capstone/ros-workspace#49]
The software runs fine on the x86 devices but for snowplow team, the arm based jetson orin will be used so the different plugs like ros2_control, urdf, gazebo, and etc will have to be ported over.

**Comment by Aduno** [comment]
Fixed URDF, virtual sensors. Ros2 control was working but not again so I have to investigate what change broke ros2_control. Additionally, slam tool box, nav2 needs to be tested again. I tried some stuff on it but its giving errors as well so one step at a time. ros2_control -> slam toolbox -> nav2

**Comment by Aduno** [comment]
Successfully tested on ARM64 with the new gazebo fortress migration.
